name: Linting Work

on:
  push:
    branches: [ develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Checkout written code
        uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Submit lint report
        uses: actions/upload-artifact@v2
        with:
          name: Fotos_lint_report.html
          path: app/build/reports/lint-results-debug.html