name: Upload To Playstore

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: assemble-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew build

  generate-release-bundle:
    needs: [ build ]
    name: Generate a release bundle
    runs-on: ubuntu-latest
    steps:
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Tell gradle to generate a release bundle
        run: ./gradlew bundleRelease

#      - name: Sign Release apk
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.BASE64_CERT }}
#          alias: ${{ secrets.KEYSTORE_ALIAS }}
#          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
##      - name: Bump version
##      uses: chkfung/android-version-actions@v1.1
##      with:
##      gradlePath: app/build.gradle.kts
##      versionCode: ${{github.run_number}}
##      versionName: 1.0.0
#
#      - name: Create service_account.json
#        run: echo '${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}' > service_account.json
#
#      - name: Deploy to Production
#        uses: r0adkll/upload-google-play@v1.0.15
#        with:
#          serviceAccountJson: service_account.json
#          packageName: com.cmaina.fotos
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: internal

#  generate-github-release:
#    name: Generate release
